### ISSUE TITLE
Neural renderer dependency

### ISSUE THREAD

**Issue by iegorval** [benjiebob/WLDO#4]
Good afternoon,

May I ask how do you install the neural renderer dependency? If I run regular `pip install`, it just fails for me.  I have tried to fix some issues there and install it manually by copying the source code, and install it from the `setup.py`. The WLDO code then seems to run, but results are pretty bad. If I compare with the image from the `README`, I can see that I have worse results (with the pre-trained network) then it probably should be.

![example](https://user-images.githubusercontent.com/23455259/124261424-0f35da00-db31-11eb-8585-5aef780d9cfb.png)

I am not 100% sure, but I guess that it might be the problem with the neural renderer dependency. Which version did you use and how did you install it? 

Thank you.

**Comment by benjiebob** [comment]
Hey - yes... something not right here :) 

Please could you let me know your OS and the command you're using to run the script. I'll try to install from scratch and provide guidance.

**Comment by iegorval** [comment]
> Hey - yes... something not right here :)
> 
> Please could you let me know your OS and the command you're using to run the script. I'll try to install from scratch and provide guidance.

Thank you for your fast answer.

I have realized that the issue was on my side :) I have used the family "dogs" for template, as I supposed that it would prefer the species-specific template, but it seems that this was what was causing an issue. Can you confirm that it is the intended use of WLDO to always have a -1 family instead of the species-specific template?

Thank you and have a nice day.

**Comment by benjiebob** [comment]
Yes, the following lines should be unchanged (i.e. set to -1) in order to reproduce our results:

https://github.com/benjiebob/WLDO/blob/master/wldo_regressor/eval.py#L32
https://github.com/benjiebob/WLDO/blob/master/wldo_regressor/demo.py#L27

**Comment by iegorval** [comment]
Thank you.

On a side node, maybe adding the information about the neural renderer installation would still be useful, as, as I have mentioned, I could not automatically install it from pip, and I know that I am not the only one. And in the version, which I have managed to finally install, I had to change `render` to `render_rgb` in `nmr.py`, so I guess it is a slightly different version from the one you used.

**Comment by benjiebob** [comment]
I agree this would be useful -- to be honest, I've struggled a bit with this library in the past. 

However, I think it would be best to raise issues specific to this library on the [Neural Renderer Pytorch](https://github.com/daniilidis-group/neural_renderer) repository where it can benefit all their users rather than just those interested in WLDO. 

I'd encourage you to raise an issue there, particularly if you had issues with pip install. 

Cheers! Will close.
