### ISSUE TITLE
Operational demo.py problem

### ISSUE THREAD

**Issue by nightmareisme** [benjiebob/WLDO#5]
self.model_renderer = NeuralRenderer(
            config.IMG_RES, proj_type=config.PROJECTION, 
            norm_f0=config.NORM_F0, 
            norm_f=config.NORM_F, 
            norm_z=config.NORM_Z)
synth_rgb, synth_silhouettes = self.model_renderer( 
            verts, faces, pred_camera)
synth_rgb = torch.clamp(synth_rgb, 0.0, 1.0)
TypeError: clamp(): argument 'input' (position 1) must be Tensor, not tuple

Is there a problem with the torch version? Or is the library now incompatible?

**Comment by Brian417-cup** [comment]
Hey, I meet the same problem. I wonder whether you have solved this problem.

**Comment by benjiebob** [comment]
Hi both, thanks for reporting. I believe this is fixed in the commit I just made. Issue was a change to the neural_renderer return arguments. The synth_rgb is the first element of the returned tuple.
